### ISSUE TITLE
DBT Model Name Tooltip Overlap in Navigation

### ISSUE THREAD

**Issue by tim-watcha** [ramonvermeulen/dbt-toolkit#109]
In the DBT model navigation view, when hovering over truncated model names to see the full name via tooltip, the tooltip sometimes overlaps with adjacent model names. This makes it difficult to read both the full name and the names of nearby models.

<img width="468" alt="스크린샷 2024-09-03 오전 11 44 08" src="https://github.com/user-attachments/assets/43effa7b-738e-41f7-8db6-99eb780f834b">

Thank you for your attention to this issue and for continuously improving the user experience of the DBT tool.

**Comment by ramonvermeulen** [comment]
Thanks for this request @tim-watcha! What would you see as the ideal behavior for such long model names? In the beginning I did not have the tool-tip functionality and it would render as one big mess. One solution could be that I can set the z-index of the model that you hover on to a higher number than the other nodes, in that case (I assume) the tool-tip will render over anything else.

**Comment by tim-watcha** [comment]
That's what I actually asked for. Sorry for wrong words!

(I actually wanted to create issue politely, so I asked LLM to make my words correct. and then 😅 ...)
