### ISSUE TITLE
Feature Request: Center Selected Model when Using Reset Button

### ISSUE THREAD

**Issue by tim-watcha** [ramonvermeulen/dbt-toolkit#110]
Thank you for your quick response to my previous request. I appreciate 😄. Here I have another re-center feature request.

## Description

Currently, the 'Reset' button in the DBT model navigation view resets the view to its default state. We propose enhancing this functionality to also center the currently selected model in the view. This feature would greatly improve navigation, especially when users lose track of their current model's position in large projects.

## Current Behavior

The Reset button returns the view to its default state without focusing on any specific model.

## Proposed Behavior
<img width="70" alt="스크린샷 2024-09-03 오전 11 43 43" src="https://github.com/user-attachments/assets/f1ae8411-4cb7-4f9d-a939-9d3228f6e322">

When the Reset button is clicked:
1. The view should reset to its default zoom level and general position.
2. The currently selected model should be centered in the view.

## Motivation

This enhancement would:
- Improve navigation efficiency in large DBT projects.
- Provide quick reorientation when users lose their place in the model view.
- Align functionality more closely with DBT Cloud, which offers a similar feature.

## Implementation Suggestions

1. Identify the currently selected model when the Reset button is clicked.
2. After resetting the view to its default state, adjust the view position to center on the selected model.
3. If no model is currently selected, maintain the current Reset button behavior.

Thank you for considering this feature request. We believe it would significantly enhance the usability of the DBT model navigation, especially for users working with large and complex projects.

**Comment by ramonvermeulen** [comment]
Thanks again @tim-watcha for the feature request! Currently the button only starts a `dbt parse` process in the background, to re-parse your project. I'll look into this functionality and see if I can add the reset of zoom and centering the currently selected model.

**Comment by ramonvermeulen** [comment]
Solved in v0.2.0 https://github.com/ramonvermeulen/dbt-toolkit/pull/191
