### ISSUE TITLE
Lineage is showing all models in the project

### ISSUE THREAD

**Issue by alejandrorial** [ramonvermeulen/dbt-toolkit#140]
The lineage is not filtering just the model selected, is showing the whole project

![image](https://github.com/user-attachments/assets/649faa3a-954b-4f5c-b537-00ae9f9a6dc4)

**Comment by ramonvermeulen** [comment]
Thanks, for opening the issue! This is indeed something that is known to me and on the list of things I want to improve the plugin on.

I will implement this with the following issue:
https://github.com/ramonvermeulen/dbt-toolkit/issues/96

Maybe if implementing full selector based filtering is too ambitious for the next release (aiming 27th of September) I might implement a simple toggle to switch between full project vs. only up/downstream.

**Comment by alejandrorial** [comment]
Amazing! Thank you so much, eager to start using this much more the toolkit!!

**Comment by ramonvermeulen** [comment]
Closing issue, will be solved with the next release.
