### ISSUE TITLE
Reverse Navigation in Lineage Mini-map: Unexpected Behavior on macOS

### ISSUE THREAD

**Issue by tim-watcha** [ramonvermeulen/dbt-toolkit#94]
![output_4x_speed](https://github.com/user-attachments/assets/6cc9e46a-f701-48b9-8424-bbec83a395eb)
I've noticed an unintuitive behavior in the vertical navigation of the lineage view's mini-map (navigation pane) while using your IntelliJ plugin on macOS. This issue affects the user experience when navigating large dbt projects.

Issue Description:
When I click and drag within the mini-map to navigate the larger lineage view, the vertical movement is reversed, while the horizontal movement works as expected. Specifically:
- Dragging the cursor up moves the view down
- Dragging the cursor down moves the view up
- Horizontal movement (left/right) works correctly

This inconsistency in behavior is confusing and makes vertical navigation feel unnatural, especially for macOS users who are accustomed to natural scrolling directions in other applications.

Expected Behavior:
The mini-map's vertical navigation should follow the direction of the cursor movement, matching the current correct horizontal behavior:
- Dragging up should move the view up
- Dragging down should move the view down
- Horizontal movement should remain as is (currently working correctly)

This would provide a consistent and intuitive user experience across both axes of movement.

I believe addressing this issue would greatly improve the usability of the lineage view, especially for projects with complex model relationships that require frequent navigation.

Thank you for your attention to this matter. I'm happy to provide any additional information or clarification if needed.

**Comment by ramonvermeulen** [comment]
@tim-watcha 

Great to see that someone is actually using the plugin! 🙌

Issues like the ones you added really help me improve the plugin and user experience.
Thank you for your detailed feature requests and bug reports.

As soon as I have some free time, I will work on these and aim for a 0.1.1 release.

**Comment by ramonvermeulen** [comment]
@tim-watcha

Could you test if this is still a problem in version 0.1.1 (as soon as it is available on the marketplace)? If so, I'll close the issue.

I updated the reactflow to version 12, and set this property explicitly to false: https://github.com/ramonvermeulen/dbt-toolkit/blob/0b88d1bb10e0d2f1a5cdece4504afa3eb4346aed/lineage-panel/src/Flow.tsx#L117

At least on linux/windows it seems to work fine.

**Comment by tim-watcha** [comment]
It works fine!

**Comment by ramonvermeulen** [comment]
Awesome, closing ticket! Thanks for the feature request :)
