### ISSUE TITLE
Feature Request: Enhance Model Lineage View - Auto-centering

### ISSUE THREAD

**Issue by ramonvermeulen** [ramonvermeulen/dbt-toolkit#95]
Split out from original issue https://github.com/ramonvermeulen/dbt-toolkit/issues/93 by @tim-watcha

I've been using your new IntelliJ plugin for dbt and have some suggestions to enhance the model lineage view, particularly for projects with a large number of models:

Auto-center on model navigation:
When navigating to a different model in the lineage view, it would be beneficial if the view automatically centered on the newly selected model. In projects with numerous models, it's currently challenging to locate the model I've navigated to, even when zoomed out. This auto-centering feature would greatly improve navigation and reduce the time spent searching for models.

This kind of filtering would make it much easier to visualize and understand relationships in complex projects with numerous models.

These enhancements would significantly improve the user experience when working with large dbt projects, making it easier to navigate and understand model relationships. As a user dealing with a substantial number of models, these features would greatly increase my productivity and the overall usability of the lineage view.

I believe these additions would set dbt-toolkit apart and make it an even more powerful tool for dbt developers using IntelliJ.

Thank you for considering these suggestions. I'm happy to provide any additional context or use cases if needed.

**Comment by ramonvermeulen** [comment]
@tim-watcha just uploaded a new version (0.1.1) where I implemented this functionality, could you test if it works correctly? Then I will close the issue.

P.s. it can take a bit before the version will get approved in the Jetbrains Marketplace.

**Comment by tim-watcha** [comment]
Absolutely! I'm thrilled to hear that. Looking forward to the next version with happy anticipation!

**Comment by ramonvermeulen** [comment]
Awesome! It is currently pending in the Jetbrains store, most of the time it takes 1 or 2 business days.
It is also possible to download the .zip archieve from the releases page, and use plugin > install from disk.

**Comment by tim-watcha** [comment]
It works fine! yay

**Comment by ramonvermeulen** [comment]
Awesome, closing ticket! Thanks for the feature request :)
